### ISSUE TITLE
Tests exit if notebook specifies python 2

### ISSUE THREAD

**Issue by vincentdavis** [tiagoantao/biopython-notebook#8]
If the notebook specifies python 2 the Travis CI tests exit. The python version is specified at the end of the notebook JSON as shown below. Travis CI error below.
```json  
 "metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.10"
  }
```

```python
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/jupyter_client/kernelspec.py", line 141, in get_kernel_spec
    resource_dir = d[kernel_name.lower()]
KeyError: 'python2'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "test/test.py", line 23, in <module>
    nb_executed, resources = ex.preprocess(nb, resources={})
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/nbconvert/preprocessors/execute.py", line 79, in preprocess
    cwd=path)
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/jupyter_client/manager.py", line 430, in start_new_kernel
    km.start_kernel(**kwargs)
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/jupyter_client/manager.py", line 231, in start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/jupyter_client/manager.py", line 171, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/jupyter_client/manager.py", line 82, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/jupyter_client/kernelspec.py", line 143, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: 'python2'
The command "python test/test.py" exited with 1.
Done. Your build exited with 1.
```

**Comment by tiagoantao** [comment]
I am confused here: none of the notebooks specify python 2, so this is OK, right?

**Comment by vincentdavis** [comment]
Pull request #7 does.
https://github.com/kozo2/biopython-notebook/commit/b71dfba4ee5443e1e4648baeda654d2116af5c17#diff-972e8239b907c76032b2adbcbb3e566cL205

**Comment by tiagoantao** [comment]
Give that this is a new project, I would strongly prefer that all development is done in Python 3. Support for Legacy versions (2 or even 1) would not be assured. I am going to update the documentation to reflect this.
